services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - bootcamp_data:/var/lib/mysql

volumes:
  bootcamp_data: